version: "3"

services:
  nextapp:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - CHROMA_API_URL=http://chromadb:8000
      - NEXT_PUBLIC_SUPABASE_URL=https://cequrbhyjgljrocnhcbv.supabase.co
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/api/health-check"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - chromadb

  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    volumes:
      - ./docker-volumes/chroma:/chroma/chroma
    ports:
      - "8000:8000"
    environment:
      - ALLOW_RESET=true
      - ANONYMIZED_TELEMETRY=false
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
