name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            # Load NVM
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            # Stop the application
            cd ~/codesherpa
            pm2 stop codesherpa
            pm2 delete codesherpa
            # Make sure we're using SSH for GitHub
            git remote set-url origin git@github.com:aetherjs/codesherpa.git
            # Pull the latest changes
            git pull origin main
            # Continue with the deployment
            npm ci
            npm run build
            pm2 start npm --name codesherpa -- run start -- -p 3000
